### ISSUE TITLE
[feature request] add enum support ?

### ISSUE THREAD

**Issue by mydearxym** [scottming/joi#1]
hi there ~

this lib is very useful, but is little inconvenient to validate enum data structure

```elixir
schema = %{
    mode: [:string, enum: ["checklist", "order_list", "unorder_list"]],
    items: [:list]
}

ok_data = %{mode: "checklist", items: ["user"]}
err_data = %{mode: "text", items: ["user"]}

Joi.validate(ok_data, schema)) # => {:ok, _}
Joi.validate(err_data, schema)) # => {:error, _}
```
any plan to support `enum:` key-word ? [custom functions](https://github.com/scottming/joi#custom-functions) is kinda "heavy" for this situation.

**Comment by scottming** [comment]
Well, your suggestion is good. In the next few days, I'll find a less busy time to add this feature to the validation options for `number` and `string`.

**Comment by scottming** [comment]
@mydearxym I've added an inclusion setting that can be used in the `:atom`, `:string` and  `:number` options, which I think should work for your needs.

https://github.com/scottming/joi/commit/423db9f3ac7cde5fd79a4167c195f6442d31bb0c
